language: rust
sudo: false
matrix:
  include:
    - rust: stable
      env:
       - NAME="stable"
       - FEATURES=''
    - rust: nightly
      env:
       - NAME="nightly"
       - FEATURES=''
       - BENCH=1
script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES" &&
      ([ "$BENCH" != 1 ] || cargo bench --verbose --features "$FEATURES")
