[package]
name = "rusticata"
version = "0.1.0"
description = "Glue layer for loading Rust parsers in Suricata"
license = "LGPL-2.1+"
keywords = ["Suricata","IDS","TLS","SSL","protocol","parser","nom"]
homepage = "https://github.com/rusticata/rusticata"
repository = "https://github.com/rusticata/rusticata.git"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[lib]
crate-type = ["dylib"]
# crate-type = ["staticlib"]

[dependencies]
libc = "0.2.0"
log = "0.3.6"
nom = {version = "^3.0", features=["verbose-errors"] }
enum_primitive = "0.1.0"
num-traits = "0.1.36"
itertools = "0.7"
md5 = "0.3"
der-parser = "0.5.2"
ipsec-parser = "0.3.0"
kerberos-parser = "0.1.3"
ntp-parser = "^0.1"
# openvpn-parser = "0.1"
# radius-parser = "0.1"
# snmp-parser = "0.1"
# ssh-parser = "0.1"
# tls-parser = "^0.5"
# x509-parser = "0.1"

# [dependencies.ntp-parser]
# path = "../ntp-parser"
# git = "https://github.com/rusticata/ntp-parser.git"

[dependencies.openvpn-parser]
# path = "../openvpn-parser"
git = "https://github.com/rusticata/openvpn-parser.git"

[dependencies.radius-parser]
# path = "../radius-parser"
git = "https://github.com/rusticata/radius-parser.git"

[dependencies.snmp-parser]
# path = "../snmp-parser"
git = "https://github.com/rusticata/snmp-parser.git"

[dependencies.ssh-parser]
# path = "../ssh-parser"
git = "https://github.com/rusticata/ssh-parser.git"

[dependencies.tls-parser]
# path = "../tls-parser"
git = "https://github.com/rusticata/tls-parser.git"

[dependencies.x509-parser]
# path = "../x509-parser"
git = "https://github.com/rusticata/x509-parser.git"
